NAME
  VTK::FiltersTemporal
LIBRARY_NAME
  vtkFiltersTemporal
KIT
  VTK::Filters
GROUPS
  StandAlone
DESCRIPTION
  Filters that process time-varying data.
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::FiltersCore
  VTK::CommonCache # VTK_DEPRECATED_IN_9_7_0 vtkDataObjectMeshCache moved there
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
TEST_DEPENDS
  VTK::CommonCache
  VTK::CommonExecutionModel
  VTK::FiltersGeneral
  VTK::FiltersHybrid
  VTK::FiltersSources
  VTK::IOXML
  VTK::InteractionStyle
  VTK::RenderingCore
  VTK::RenderingOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
